(autoload 'cssh-define-global-bindings          "cssh" "" t)
(autoload 'cssh-term-remote-open                "cssh" "" t)
(autoload 'cssh-regexp-host-start               "cssh" "" t)
(autoload 'cssh-ibuffer-start                   "cssh" "" t)
(autoload 'cssh-dired-find-file                 "cssh" "" t)
(autoload 'cssh-bol                             "cssh" "" t)
(autoload 'cssh-mode                            "cssh" "" t)
(autoload 'cssh-send-tab                        "cssh" "" t)
(autoload 'cssh-cancel-input                    "cssh" "" t)
(autoload 'cssh-send-input                      "cssh" "" t)
(autoload 'cssh-clear                           "cssh" "" t)
(autoload 'cssh-eof                             "cssh" "" t)
(autoload 'cssh-reopen                          "cssh" "" t)
(autoload 'cssh-reconnect-ssh                   "cssh" "" t)
(provide 'cssh-mode-epkg-install)
